# Generated by Django 2.2.9 on 2020-02-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200208_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPosition',
            new_name='ProductInCart',
        ),
    ]
